#!/bin/sh
# WSL
#export DISPLAY=$(grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'):0
#export LIBGL_ALWAYS_INDIRECT=1

# Vim
export VIM_CONFIG=$HOME/.config/vim

# Cargo
export PATH="${PATH}:${HOME}/.cargo/bin"

# Python
export PATH=$HOME/bin:$PATH

export PATH=$HOME/.local/bin:$PATH

